# Generated by Django 3.0.2 on 2020-02-04 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('user_name', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('item_list', models.TextField()),
                ('date', models.DateField()),
                ('address', models.TextField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('type', models.CharField(choices=[('PUB', 'Public'), ('PER', 'Personal')], default='PER', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.TextField()),
                ('password', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('info', models.TextField()),
                ('operating_locations', models.TextField()),
                ('item_list', models.TextField()),
                ('state', models.CharField(choices=[('S', 'Suspended'), ('A', 'Activated')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recycler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('state', models.CharField(choices=[('S', 'Suspended'), ('A', 'Activated')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SuspensionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('request_message', models.TextField()),
                ('password', models.TextField()),
                ('account', models.CharField(choices=[('O', 'Organization'), ('S', 'Standard')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDisposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_list', models.TextField()),
                ('date', models.DateField()),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Recycler')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationPerformence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('handled_date', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_list', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('H', 'Handled'), ('U', 'Unhandled')], default='U', max_length=1)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alert')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Recycler'),
        ),
    ]
