# Generated by Django 3.0.2 on 2020-02-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='langitude',
            new_name='latitude',
        ),
    ]
