# Generated by Django 3.0.2 on 2020-02-07 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200208_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationperformence',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='organizationperformence',
            name='handled_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
