# Generated by Django 3.0.2 on 2020-02-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200208_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalerts',
            name='item_list',
        ),
    ]
