# Generated by Django 3.0.2 on 2020-02-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_organizationalerts_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='book_status',
            field=models.CharField(choices=[('B', 'B'), ('UN', 'UN')], default='UN', max_length=2),
        ),
    ]
