# Generated by Django 3.0.2 on 2020-02-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alert_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='book_status',
            field=models.CharField(choices=[('B', 'Booked'), ('UB', 'Unbooked')], default='UB', max_length=2),
        ),
    ]
