# Generated by Django 3.0.2 on 2020-07-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_personaldisposal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycler_email', models.TextField()),
                ('org_email', models.TextField()),
                ('confirmation', models.CharField(choices=[('C', 'Checked'), ('U', 'Unchecked')], default='U', max_length=1)),
                ('response', models.CharField(choices=[('H', 'Handled'), ('UH', 'Unhandled'), ('IN', 'Inconclusive')], default='IN', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='personaldisposal',
            name='type',
            field=models.CharField(choices=[('PUB', 'Public'), ('PER', 'Personal'), ('SAV', 'Unreported')], default='PER', max_length=3),
        ),
    ]
