# Generated by Django 3.0.2 on 2020-07-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200726_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertconfirmation',
            name='confirmation',
            field=models.CharField(choices=[('C', 'Checked'), ('U', 'Unchecked')], default='U', max_length=2),
        ),
    ]
