# Generated by Django 3.0.2 on 2020-07-26 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200726_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfirmation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='alertconfirmation',
            name='item_list',
            field=models.TextField(default=None),
        ),
    ]
