from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add_user/', views.add_recycler),
    path('get_user/', views.get_recycler),
    path('verify_r_email/', views.verify_r_email),
    path('verify_r_username/', views.verify_r_username),
    path('verify_r_phone/', views.verify_r_phone),
    path('verify_org_email/', views.verify_org_email),
    path('verify_org_username/', views.verify_org_username),
    path('verify_org_phone/', views.verify_org_phone),
    path('add_org/', views.add_org),
    path('get_org/', views.get_org),
    path('login_recycler/', views.login_recycler),
    path('login_org/', views.login_org),
    path('login_admin/', views.login_admin),
    path('suspend_recycler/', views.suspend_recycler),
    path('suspend_org/', views.suspend_org),
    path('suspend_reqs/', views.suspend_reqs),
    path('add_sus_rep/', views.add_sus_rep),
    path('update_org/', views.update_org),
    path('update_rec/', views.update_rec),
    path('add_alert/', views.add_alert),
    path('get_all_alerts/', views.get_all_alerts),
    path('get_alert/', views.get_alert),
    path('get_org_performence/', views.get_org_performence),
    path('add_org_performence/', views.add_org_performence),
    path('add_disposal_info/', views.add_disposal_info),
    path('get_disposal_info/', views.get_disposal_info),
    path('add_org_alert/', views.add_org_alert),
    path('unbook_alert/', views.unbook_alert),
    path('change_org_alert_status/', views.change_org_alert_status),
    path('get_org_alerts/', views.get_org_alerts),
    path('cancel_suspend/', views.cancel_suspend),
    path('get_rec_alerts/', views.get_rec_alerts),
    path('get_rec_alert_conf/', views.get_rec_alert_conf),
    path('get_org_alert_conf/', views.get_org_alert_conf),
    path('update_alert_conf/', views.update_alert_conf),
    path('add_alert_conf/', views.add_alert_conf),
    path('send_code/', views.send_code),
    path('add_org_photo/', views.add_org_photo),
    path('add_alert_photo/', views.add_alert_photo)
]